#!/bin/sh

g++ -std=c++14 analiz.cpp clicker.cpp GUI/font.cpp global.cpp main.cpp mikrotik.cpp program.cpp tools.cpp sessions.cpp sniffer.cpp pcap.cpp frame.cpp fragments_queue.cpp webcam.cpp GUI/GUI.cpp GUI/GUI_Element.cpp GUI/GUI_Linux.cpp GUI/GUI_Primitives.cpp -o sniffer -pthread -lX11 -lXtst